# Generated by Django 3.1.5 on 2021-01-12 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_name', models.CharField(max_length=4096)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.PositiveSmallIntegerField(default=1000)),
                ('delay_until', models.DateTimeField(null=True)),
                ('max_retries', models.PositiveSmallIntegerField(default=0)),
                ('base_retry_delay', models.DurationField(default=datetime.timedelta(seconds=1))),
                ('retry_multiplier', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='JobResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('exception', models.TextField()),
                ('traceback', models.TextField()),
                ('result', models.JSONField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbqueue.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobKWArg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=255)),
                ('arg', models.JSONField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kwargs', to='dbqueue.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobArg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('arg', models.JSONField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='args', to='dbqueue.job')),
            ],
            options={
                'unique_together': {('job', 'position')},
            },
        ),
    ]
