# Generated by Django 3.1.5 on 2021-01-12 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbqueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresult',
            name='permanent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobresult',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dbqueue.job'),
        ),
    ]
