# Generated by Django 3.1.5 on 2021-01-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbqueue', '0002_auto_20210112_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='error_delay_until',
            field=models.DateTimeField(null=True),
        ),
    ]
