# Generated by Django 3.1.5 on 2021-01-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbqueue', '0003_job_error_delay_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
